services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Tokyo
      - PGTZ=Asia/Tokyo
    env_file:
      - ./postgres/.env
    restart: always