-- usersテーブル作成
CREATE TABLE IF NOT EXISTS users(
	id SERIAL PRIMARY KEY,
	email VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	name VARCHAR(100) NOT NULL,
	roles VARCHAR(100)
);

-- recipesテーブル作成
CREATE TABLE IF NOT EXISTS recipe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    main_ingredient VARCHAR(255),
    name VARCHAR(255),
    other_ingredients VARCHAR(255)[],
    url VARCHAR(255)
);

-- データ挿入
INSERT INTO users (id, email, password, name, roles) VALUES
(1, 'admin@example.com', '$2a$10$Ff.Tr2q.fBciJKiA1b4wAOwNpjr9RypX3DHeQwLQQg0GMxGrl4FcO', 'admin', 'ADMIN'),
(2, 'student@example.com', '$2a$10$fzJDR7BSMQnRg9Odg/JDzemQdLc6g2a7lR/ccHoMQEoxpxhs6dT0m', 'student', 'USER');

INSERT INTO recipe (main_ingredient, name, other_ingredients, url) VALUES
('beef', 'Beef Stroganoff', ARRAY['onion', 'mushroom', 'sour cream'], 'https://www.simplyrecipes.com/recipes/beef_stroganoff/'),
('chicken', 'Chicken Alfredo', ARRAY['fettuccine', 'parmesan', 'garlic'], 'https://www.sim');